version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "primary-stack"
s3_prefix = "primary-stack"
region = "eu-central-1"
capabilities = "CAPABILITY_IAM CAPABILITY_AUTO_EXPAND CAPABILITY_NAMED_IAM"
parameter_overrides = "AppName=\"photo-blog-application\" StageName=\"dev\" DomainName=\"auth.mscv2group1.link\" FrontendBucketName=\"frontend-assests-145023116067\" EmailSender=\"notifications@mscv2group1.link\" BackupRegion=\"eu-west-1\" BackupBucketArn=\"arn:aws:s3:::photo-blog-application-dev-backup-eu-west-1-145023116067\" BackupUserPoolId=\"eu-west-1_MKjejvoK4\" BackupUserPoolClientId=\"4gd0rbjkirnvn3849d9a9p4dk7\""
confirm_changeset = true
fail_on_empty_changeset = false
tags = "project=\"MSC2\" application=\"PhotoBlog\""
resolve_s3 = true
disable_rollback = true
image_repositories = []

[prod]
[prod.deploy]
[prod.deploy.parameters]
stack_name = "photoblog-backend-prod"
s3_prefix = "photoblog-backend-prod"
region = "eu-west-1"
capabilities = "CAPABILITY_IAM CAPABILITY_AUTO_EXPAND CAPABILITY_NAMED_IAM"
parameter_overrides = "Stage=\"prod\" DomainName=\"mscv2group1.link\" DisasterRecoveryRegion=\"eu-central-1\""
confirm_changeset = true
fail_on_empty_changeset = false
tags = "project=\"MSC2\" application=\"PhotoBlog\" environment=\"production\""