version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "photoblog-backend-dev"
s3_prefix = "photoblog-backend-dev"
region = "eu-west-1"
capabilities = "CAPABILITY_IAM CAPABILITY_AUTO_EXPAND CAPABILITY_NAMED_IAM"
parameter_overrides = "AppName=\"photo-blog-app\" StageName=\"dev\" DomainName=\"mscv2group1.link\" FrontendBucketName=\"photo-blog-frontend-assets\" EmailSender=\"notifications@mscv2group1.link\" PrimaryRegion=\"eu-west-1\" BackupRegion=\"eu-central-1\""
confirm_changeset = true
fail_on_empty_changeset = false
tags = "project=\"MSC2\" application=\"PhotoBlog\""
resolve_s3 = true
image_repositories = []

[prod]
[prod.deploy]
[prod.deploy.parameters]
stack_name = "photoblog-backend-prod"
s3_prefix = "photoblog-backend-prod"
region = "eu-west-1"
capabilities = "CAPABILITY_IAM CAPABILITY_AUTO_EXPAND CAPABILITY_NAMED_IAM"
parameter_overrides = "Stage=\"prod\" DomainName=\"mscv2group1.link\" DisasterRecoveryRegion=\"eu-central-1\""
confirm_changeset = true
fail_on_empty_changeset = false
tags = "project=\"MSC2\" application=\"PhotoBlog\" environment=\"production\""