package com.photoblog.models;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
@DynamoDBTable(tableName = "")
public class Photo {
    static {
        String tableName = System.getenv("PHOTOS_TABLE");
        if (tableName != null && !tableName.isEmpty()) {
            DynamoDBMapperConfig.Builder builder = DynamoDBMapperConfig.builder();
            builder.setTableNameOverride(DynamoDBMapperConfig.TableNameOverride.withTableNameReplacement(tableName));
            builder.build();
        }
    }

    @DynamoDBHashKey
    @DynamoDBAttribute(attributeName = "userId")
    private String userId;

    @DynamoDBRangeKey
    @DynamoDBAutoGeneratedKey
    @DynamoDBAttribute(attributeName = "photoId")
    private String photoId;

    @DynamoDBAttribute
    private String imageName;

    @DynamoDBAttribute
    @DynamoDBTypeConvertedEnum
    private Status status;

    @DynamoDBAttribute
    private String createdAt;

    @DynamoDBAttribute
    private String updatedAt;

    @DynamoDBAttribute
    private String versionId;

    public enum Status{
        ACTIVE,
        DELETED
    }
}