#name: Deploy Photo Blog Backend
#
#on:
#  push:
#    branches:
#      - dev
#      - main
#
#jobs:
#  deploy:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v3
#
#      - name: Set up JDK 21
#        uses: actions/setup-java@v3
#        with:
#          distribution: 'temurin'
#          java-version: '21'
#
#      - name: Configure AWS credentials
#        uses: aws-actions/configure-aws-credentials@v2
#        with:
#          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#          aws-region: ${{ secrets.AWS_REGION }}
#
#      - name: Determine environment
#        id: env
#        run: |
#          if [[ ${{ github.ref }} == 'refs/heads/main' ]]; then
#            echo "environment=prod" >> $GITHUB_OUTPUT
#          else
#            echo "environment=dev" >> $GITHUB_OUTPUT
#          fi
#
#      - name: Build project
#        run: mvn clean package -DskipTests
#
#      - name: Deploy with SAM
#        run: |
#          if [[ ${{ steps.env.outputs.environment }} == 'prod' ]]; then
#            sam deploy \
#              --config-file samconfig.toml \
#              --config-env prod \
#              --no-confirm-changeset \
#              --no-fail-on-empty-changeset \
#              --resolve-s3
#          else
#            sam deploy \
#              --config-file samconfig.toml \
#              --config-env default \
#              --no-confirm-changeset \
#              --no-fail-on-empty-changeset \
#              --resolve-s3
#          fi
