name: Deploy Backup Region

on:
  push:
    branches: [ main, dev ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Deploy CloudFormation stack
        run: |
          aws cloudformation deploy \
            --template-file backup-template.yaml \
            --stack-name photo-blog-backup \
            --parameter-overrides \
              AppName=photo-blog-application-group1 \
              StageName=dev \
              PrimaryRegion=eu-west-1 \
              PrimaryAccountId=${{ secrets.AWS_ACCOUNT_ID }} \
            --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM

      - name: Export backup resources
        id: export-resources
        run: |
          BACKUP_BUCKET_ARN=$(aws cloudformation describe-stacks \
            --stack-name photo-blog-backup \
            --query "Stacks[0].Outputs[?OutputKey=='BackupBucketArn'].OutputValue" \
            --output text)
          
          BACKUP_USER_POOL_ID=$(aws cloudformation describe-stacks \
            --stack-name photo-blog-backup \
            --query "Stacks[0].Outputs[?OutputKey=='BackupUserPoolId'].OutputValue" \
            --output text)
          
          BACKUP_USER_POOL_CLIENT_ID=$(aws cloudformation describe-stacks \
            --stack-name photo-blog-backup \
            --query "Stacks[0].Outputs[?OutputKey=='BackupUserPoolClientId'].OutputValue" \
            --output text)
          
          echo "BACKUP_BUCKET_ARN=$BACKUP_BUCKET_ARN" >> $GITHUB_ENV
          echo "BACKUP_USER_POOL_ID=$BACKUP_USER_POOL_ID" >> $GITHUB_ENV
          echo "BACKUP_USER_POOL_CLIENT_ID=$BACKUP_USER_POOL_CLIENT_ID" >> $GITHUB_ENV
          
          echo "Backup Bucket ARN: $BACKUP_BUCKET_ARN"
          echo "Backup User Pool ID: $BACKUP_USER_POOL_ID"
          echo "Backup User Pool Client ID: $BACKUP_USER_POOL_CLIENT_ID"
          
          # Save as GitHub repository variables for the primary workflow
          echo "BACKUP_BUCKET_ARN=$BACKUP_BUCKET_ARN" >> $GITHUB_OUTPUT
          echo "BACKUP_USER_POOL_ID=$BACKUP_USER_POOL_ID" >> $GITHUB_OUTPUT
          echo "BACKUP_USER_POOL_CLIENT_ID=$BACKUP_USER_POOL_CLIENT_ID" >> $GITHUB_OUTPUT
